import { useState, useCallback } from 'react'

import { qlikService, qlikLoaderService } from '@libs/qlik-services'

const useQlikConnect = () => {
    const [qAction, setQAction] = useState<any>({ loading: false, qResponse: null, error: null })

    const setQlikConnect = useCallback(
        async (
            config: any,
            stylesUrl = 'resources/autogenerated/qlik-styles.css',
            javascriptUrl = 'resources/assets/external/requirejs/require.js'
        ) => {
            try {
                const qlik = await qlikLoaderService.loadQlikAssets({
                    host: config.host,
                    stylesUrl,
                    javascriptUrl,
                    virtualProxy: config?.prefix || '',
                    webIntegrationId: config?.webIntegrationId || '',
                    token: config?.token || ''
                })
                const qApi = await qlikService.setQixCapabilityService({
                    qlik,
                    config
                })
                setQAction({ loading: false, qResponse: qApi, error: null })
                return qApi
            } catch (error) {
                setQAction({ loading: false, qResponse: null, error: error })
                return null
            }
        },
        []
    )

    return { qAction, setQlikConnect }
}

export default useQlikConnect
