export const QIX_ERROR_CODES = {
    '-128': 'Internal engine error',
    '-1': 'Unknown error',
    '0': 'Unknown error',
    '1': 'Some data is not correctly specified.',
    '2': 'The resource could not be found.',
    '3': 'Resource already exists.',
    '4': 'Invalid path',
    '5': 'Access is denied',
    '6': 'The system is out of memory.',
    '7': 'Not initialized',
    '8': 'Invalid parameters',
    '9': 'Some parameters are empty.',
    '10': 'Internal error',
    '11': 'Corrupted data',
    '12': 'Memory inconsistency',
    '13': 'Action was aborted unexpectedly.',
    '14': 'Validation cannot be performed at the moment. Please try again later.',
    '15': 'Operation aborted',
    '16': 'Connection lost. Make sure that Qlik Sense is running properly. If your session has timed out due to inactivity, refresh to continue working.',
    '1000': 'An app with this name already exists. Please choose another name.',
    '1001': 'An app name must not include  \\\\/:<>|\\"?*',
    '1002': 'App is already open.',
    '1003': 'The app you specified could not be found.',
    '1004': 'The app could not be imported or created.',
    '1005': 'The app could not be saved. Check if it is read only.',
    '1006': 'The app was not created.',
    '1007': 'Failed to get app because there is no app loaded.',
    '1008': 'Could not connect to the opened app.',
    '1009': 'You cannot open an app both with and without data. Close all tabs where the app is already open and open the app again.',
    '1010': 'The migration service could not be started.',
    '1011': 'The app migration could not be started.',
    '2000': 'Connection with the given name already exists.',
    '2001': 'Connection not found.',
    '2002': 'Failed to load connection.',
    '2003': 'Failed to import connection.',
    '2004': 'Invalid connection name. Please enter a new connection name of 1-256 characters, without using \\ / : * ? " < > |',
    '3000': 'File access is denied.',
    '3001': 'File name is invalid.',
    '3002': 'The app file you are attempting to load from is corrupt.',
    '3003': 'A file belonging to the loaded or imported app could not be found.',
    '3004': 'Unsupported file format',
    '4000': 'You cannot access the requested resource.',
    '4001': 'The system failed to log you in.',
    '5000': 'Server has no more session and usage Client Access Licences.',
    '5001': 'Server has no more session Client Access Licences.',
    '5002': 'Server has no more usage Client Access Licences.',
    '5003': 'Server has no more Client Access Licences.',
    '5004': 'Server has no more named Client Access Licences.',
    '5005': 'Server off duty',
    '5006': 'Server busy',
    '5007': 'The license has expired. Please update to a current version to receive a new license.',
    '5008': 'AJAX is disabled.',
    '6000': 'Invalid hypercube object.',
    '6001': 'The hypercube results are too large.',
    '6002': 'Invalid hypercube object state.',
    '6003': 'Not currently possible to perform the requested operation.',
    '7000': 'All expressions are disabled',
    '7001': 'Dimension or measure not in library',
    '7002': 'Out of calculation memory',
    '7003': 'Calculation set is too large',
    '7004': 'Calculation timed out',
    '7005': 'The calculation condition is not fulfilled',
    '7006': 'Mixed DBMS and in-memory aggregation is not supported',
    '7007': 'Direct query attempted against missing or non-direct table',
    '7008': 'Invalid sort order in properties',
    '7009': 'The calculation page is too large. Reduce the number of cells and try again.',
    '7010': 'Semantic fields are not allowed in calculation',
    '7011': 'The calculation of the object could not be performed successfully. Try refreshing the app.',
    '7012': 'The dimension is already in use.',
    '7013': 'An object is referring to a Direct Discovery field that does not exist. Please update the definition of the object or add the missing field in the Direct Discovery table.',
    '8000': 'Invalid identifier for the linked object',
    '8001': 'Linked object not found on layout',
    '8002': 'Invalid linked object',
    '9000': 'The object could not be saved.',
    '9001': 'The object could not be read.',
    '9002': 'The object could not be deleted.',
    '9003': 'The object could not be found.',
    '9004': 'You are using Qlik Sense Desktop instead of Qlik Sense, or you are using the wrong version of Qlik Sense.',
    '9005': 'The app migration failed because the app is write-protected.',
    '9006': 'The app migration was cancelled. Open the app again to migrate it.',
    '9007': 'The app migration could not back up the app. The app migration is cancelled.',
    '9008': 'Insufficient disk space for operation',
    '9009': 'You are trying to use a method that is not supported in session apps',
    '9510': 'Invalid parameter sent from the repository in the binary sync protocol',
    '9511': 'Invalid parameter sent from the repository in the binary sync protocol',
    '10000': 'You do not have access to the data source.',
    '11000': 'Reload in progress.',
    '12000':
        'There is a new version of Qlik Sense Desktop available. Please update to the new version.',
    '12001': 'Your version of Qlik Sense Desktop has expired.',
    '12002':
        'Section access information was detected. This is not supported in Qlik Sense Desktop. To be able to load data into Qlik Sense Desktop, make sure to remove any section access information using a version that supports this.',
    '12003': 'Because the app is open, it cannot be deleted. Please close the app and try again.',
    '12004': 'User is not authenticated. Please log in to Qlik Sense Desktop.',
    '13000':
        'You have reached the size limitation of the export process. Please reduce the number of values to export or change the settings.',
    '13001':
        'There is no data to export. Please make sure the data in your visualization is correct.',
    '-32600': 'Invalid JSON protocol request',
    '-32601': 'Requested protocol method does not exist',
    '-32602': 'Invalid JSON protocol parameters',
    '-32603': 'Internal JSON protocol error',
    '-32700': 'JSON protocol parse error'
}

export const QLIK_JAVASCRIPT_PATH = 'resources/assets/external/requirejs/require.js'
export const QLIK_STYLES_PATH = 'resources/autogenerated/qlik-styles.css'
export const QLIK_CHAT_PATH = 'resources/hub/external/hubchat/hub-chat-ui.js'
export const QLIK_SAAS_JWT_LOGIN_PATH = 'login/jwt-session'
export const QLIK_SAAS_JWT_PATH = 'qlik/saas/jwt/login'
export const QLIK_SAAS_CSRF_TOKEN_PATH = 'api/v1/csrf-token?qlik-web-integration-id='
