import { QplusSettings, QplusApiEnum, QplusAuthModeEnum } from '@databridge/qplus-types'
import { qplusUtilService } from '@databridge/qplus'

import { SplashScreen } from 'app/layout/SplashScreen'
import { TQlikApp } from 'app/context/AppContext'

import { env } from 'env'

export const getQlikConfig = (
    hostname: string,
    virtualProxy,
    qlikApps: TQlikApp[] = [],
    theme,
    handleQlikAccessDeniedCallback: any,
    handleQlikClosedCallback: any
): QplusSettings => {
    return {
        qAuthMode: QplusAuthModeEnum.QES,
        qApi: QplusApiEnum.CAPABILITY_API,
        qConfig: {
            host: hostname,
            identity: qplusUtilService.generateIdendity(),
            prefix: virtualProxy
        },
        qAssetPaths: {
            qStyles: 'resources/autogenerated/qlik-styles.css',
            requireJs: 'resources/assets/external/requirejs/require.js',
            hubChartUiJs: 'resources/hub/external/hubchat/hub-chat-ui.js'
        },
        qTheme: theme,
        qGlobalEvents:
            env.REACT_APP_QLIK_GLOBAL_EVENTS?.split(',') ??
            process.env.REACT_APP_QLIK_GLOBAL_EVENTS?.split(','),
        qApps: qlikApps,
        LoadingComponent: SplashScreen,
        onQlikGlobalAccessDeniedCallback: handleQlikAccessDeniedCallback,
        onQlikClosed: handleQlikClosedCallback
    }
}
