import {
    QplusSettings,
    QplusApiEnum,
    QplusAuthModeEnum,
    QplusDeviceTypeEnum
} from "@databridge/qplus-types";
import { qplusUtilService } from "@databridge/qplus";

import { SplashScreen } from "app/layout/SplashScreen";
import { TQlikApp } from "app/context/AppContext";

export const getQlikConfig = (
    hostname: string,
    virtualProxy,
    theme,
    handleQlikAccessDeniedCallback: (message: string, appId?: string) => void,
    handleQlikClosedCallback: (close: unknown) => void,
    qlikApps: TQlikApp[] = []
): QplusSettings => ({
    qAuthMode: QplusAuthModeEnum.QES,
    qApi: QplusApiEnum.CAPABILITY_API,
    qDeviceType: QplusDeviceTypeEnum.DESKTOP,
    qConfig: {
        host: hostname,
        identity: qplusUtilService.generateIdendity(),
        prefix: virtualProxy
    },
    qAssetPaths: {
        qStyles: "resources/autogenerated/qlik-styles.css",
        requireJs: "resources/assets/external/requirejs/require.js",
        hubChartUiJs: "resources/hub/external/hubchat/hub-chat-ui.js"
    },
    qTheme: theme,
    qGlobalEvents: window.env.VITE_QLIK_GLOBAL_EVENTS?.split(",") ?? [],
    qApps: qlikApps,
    LoadingComponent: SplashScreen,
    onQlikGlobalAccessDeniedCallback: handleQlikAccessDeniedCallback,
    onQlikClosedCallback: handleQlikClosedCallback
});

export const localization = "localization";
export const fieldIsGuard = "isGuard";
export const varIsUserGuard = "vQlikGuardUser";
export const expIsUserGuard = `=num($(vShowSources))`;
export const varLanguage = "vLanguage";
export const hiddenTagOptions = "$hidden";
